- name: To create folder of {{ item }}
  community.general.jenkins_job:
    config: "{{ lookup('template', 'templates/folder.xml') }}"
    name: "{{ item }}"
    password: 12345
    url: http://jenkins.azcart.online:8080
    user: chaitu1812

