- name: To create {{ item.component }} job
  community.general.jenkins_job:
    config: "{{ lookup('template', 'templates/m_job.xml') }}"
    name: "{{ folder }}/{{ item.component }}"
    password: 12345
    url: http://jenkins.azcart.online:8080
    user: chaitu1812